# Generated by Django 5.2.8 on 2025-12-01 13:01

import ckeditor_uploader.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nom de la catégorie.', max_length=100, unique=True, verbose_name='Nom')),
                ('slug', models.SlugField(blank=True, help_text='Généré automatiquement à partir du nom.', max_length=120, unique=True)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Description de la catégorie avec support HTML, images, etc.', verbose_name='Description')),
                ('image', models.ImageField(blank=True, help_text='Image de la catégorie (optionnel).', null=True, upload_to='categories/')),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Titre de l'article.", max_length=255, verbose_name='Titre')),
                ('slug', models.SlugField(blank=True, help_text='Slug généré automatiquement.', max_length=255, unique=True)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(help_text="Contenu principal de l'article avec éditeur HTML riche.", verbose_name='Contenu')),
                ('excerpt', models.TextField(blank=True, help_text="Court extrait de l'article pour les listes (optionnel).", max_length=500, verbose_name='Extrait')),
                ('image', models.ImageField(blank=True, help_text='Image principale (optionnel).', null=True, upload_to='articles/')),
                ('author', models.CharField(blank=True, help_text="Nom de l'auteur", max_length=100, verbose_name='Auteur')),
                ('tags', models.CharField(blank=True, help_text='Tags séparés par des virgules.', max_length=200)),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('published', 'Publié'), ('archived', 'Archivé')], default='draft', help_text='Statut de publication.', max_length=10, verbose_name='Statut')),
                ('views', models.PositiveIntegerField(default=0, help_text="Nombre de vues de l'article.", verbose_name='Vues')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de publication')),
                ('meta_description', models.CharField(blank=True, help_text='Description SEO (max 160 caractères).', max_length=160, verbose_name='Meta description')),
                ('meta_keywords', models.CharField(blank=True, help_text='Mots-clés SEO séparés par des virgules.', max_length=255, verbose_name='Mots-clés SEO')),
                ('category', models.ForeignKey(blank=True, help_text="Catégorie de l'article.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='blog.category', verbose_name='Catégorie')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
                'ordering': ['-published_at', '-created_at'],
                'indexes': [models.Index(fields=['-published_at'], name='blog_articl_publish_308f23_idx'), models.Index(fields=['status'], name='blog_articl_status_57fc64_idx')],
            },
        ),
    ]
