# Generated by Django 5.2.8 on 2026-01-31 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='video_file',
            field=models.FileField(blank=True, help_text='Télécharger une vidéo (MP4, WebM, etc.).', null=True, upload_to='articles/videos/', verbose_name='Fichier vidéo'),
        ),
        migrations.AddField(
            model_name='article',
            name='video_url',
            field=models.URLField(blank=True, help_text='Lien vers une vidéo (YouTube, Vimeo, etc.). Si une vidéo est téléchargée, ce lien sera ignoré.', verbose_name='Lien vidéo'),
        ),
    ]
