# Generated by Django 5.2.8 on 2026-03-26 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomeSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_badge', models.CharField(blank=True, max_length=100)),
                ('hero_title_prefix', models.CharField(blank=True, max_length=200)),
                ('hero_title_suffix', models.CharField(blank=True, max_length=200)),
                ('hero_description', models.TextField(blank=True)),
                ('hero_right_image', models.ImageField(blank=True, null=True, upload_to='home/hero/')),
                ('hero_stats_youth_mentored', models.PositiveIntegerField(blank=True, null=True)),
                ('hero_stats_years_experience', models.PositiveIntegerField(blank=True, null=True)),
                ('hero_stats_continents', models.PositiveIntegerField(blank=True, null=True)),
                ('quote_text', models.TextField(blank=True)),
                ('quote_subtext', models.CharField(blank=True, max_length=255)),
                ('quote_author_role', models.CharField(blank=True, max_length=255)),
                ('quote_cta', models.CharField(blank=True, max_length=100)),
                ('quote_image', models.ImageField(blank=True, null=True, upload_to='home/quote/')),
                ('vision_badge', models.CharField(blank=True, max_length=100)),
                ('vision_title', models.CharField(blank=True, max_length=255)),
                ('vision_description', models.TextField(blank=True)),
                ('values_leadership_title', models.CharField(blank=True, max_length=200)),
                ('values_leadership_desc', models.TextField(blank=True)),
                ('values_excellence_title', models.CharField(blank=True, max_length=200)),
                ('values_excellence_desc', models.TextField(blank=True)),
                ('values_impact_title', models.CharField(blank=True, max_length=200)),
                ('values_impact_desc', models.TextField(blank=True)),
                ('barika_desc', models.TextField(blank=True)),
                ('barika_education_title', models.CharField(blank=True, max_length=200)),
                ('barika_education_desc', models.TextField(blank=True)),
                ('barika_sport_title', models.CharField(blank=True, max_length=200)),
                ('barika_sport_desc', models.TextField(blank=True)),
                ('barika_entrepreneurship_title', models.CharField(blank=True, max_length=200)),
                ('barika_entrepreneurship_desc', models.TextField(blank=True)),
                ('barika_cta', models.CharField(blank=True, max_length=100)),
                ('join_badge', models.CharField(blank=True, max_length=100)),
                ('join_title_prefix', models.CharField(blank=True, max_length=255)),
                ('join_desc', models.TextField(blank=True)),
                ('join_cta', models.CharField(blank=True, max_length=100)),
                ('articles_title_prefix', models.CharField(blank=True, max_length=255)),
                ('articles_title_suffix', models.CharField(blank=True, max_length=255)),
                ('articles_desc', models.TextField(blank=True)),
                ('articles_view_all', models.CharField(blank=True, max_length=100)),
                ('articles_read_more', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': "Paramètres d'accueil",
                'verbose_name_plural': "Paramètres d'accueil",
            },
        ),
        migrations.CreateModel(
            name='HomeGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='home/gallery/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='homepage.homesettings')),
            ],
            options={
                'verbose_name': 'Image de galerie',
                'verbose_name_plural': 'Images de galerie',
                'ordering': ['order', 'id'],
            },
        ),
    ]
