# Generated by Django 5.2.8 on 2026-05-20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_aboutpagesettings_contactmessage_contactpagesettings_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='about/gallery/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='homepage.aboutpagesettings')),
            ],
            options={
                'verbose_name': 'Image galerie (À propos)',
                'verbose_name_plural': 'Images galerie (À propos)',
                'ordering': ['order', 'id'],
            },
        ),
    ]
