# Generated by Django 5.2.8 on 2026-06-02 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0011_block_image_max_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='email_sent',
            field=models.BooleanField(default=False, help_text='Ancienne notification SMTP (non utilisée si e-mail désactivé).'),
        ),
    ]
